name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  clean:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # 并行移除
      - name: Delete workflow runs for current repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 2
          repository: '${{ github.repository }}'
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.propertiea') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # This is needed to be able to run ./gradlew below
      # You can run `git update-index --chmod +x gradlew` then remove this step.
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Gmm with Gradle
        run: ./gradlew gmm

      - name: Crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          pull_request_title: '[Dove] Crowdin Pull request'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DOVE_CROWDIN_PROJECT_ID: ${{ secrets.DOVE_CROWDIN_PROJECT_ID }}
          DOVE_CROWDIN_API_TOKEN: ${{ secrets.DOVE_CROWDIN_API_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build
