name: crowdin
on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 1 * * *"
    - cron: "0 2 * * *"
    - cron: "0 3 * * *"
    - cron: "0 4 * * *"
    - cron: "0 5 * * *"
    - cron: "0 6 * * *"
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"
    - cron: "0 9 * * *"
    - cron: "0 10 * * *"
    - cron: "0 11 * * *"
    - cron: "0 12 * * *"
    - cron: "0 13 * * *"
    - cron: "0 14 * * *"
    - cron: "0 15 * * *"
    - cron: "0 16 * * *"
    - cron: "0 17 * * *"
    - cron: "0 18 * * *"
    - cron: "0 19 * * *"
    - cron: "0 20 * * *"
    - cron: "0 21 * * *"
    - cron: "0 22 * * *"
    - cron: "0 23 * * *"
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Check directory exists
        uses: andstor/file-existence-action@v3
        id: check_directory
        with:
          files: "crowdin/"
      - name: Copy Language by Crowdin
        run: |
          cp src/act/generated/assets/dove_act/lang/en_us.json crowdin/dove_act.json
          cp src/pack/generated/assets/dove_pack/lang/en_us.json crowdin/dove_pack.json
      - name: Commit and push changes
        run: |
          git add crowdin/
          git commit -m "Language Update to Crowdin" || echo "No changes to commit"
          git push
      - name: Crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DOVE_CROWDIN_PROJECT_ID: ${{ secrets.DOVE_CROWDIN_PROJECT_ID }}
          DOVE_CROWDIN_API_TOKEN: ${{ secrets.DOVE_CROWDIN_API_TOKEN }}



